## Practice 1: Creating Arrays

**Q1.** Create a 1D array of numbers from 10 to 50 using NumPy.

In [2]:
import numpy as np
a = np.arange(10, 51)
print(a)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


**Q2.** Create a 2D array of shape (3, 4) filled with ones.

In [3]:
import numpy as np
a = np.ones((3, 4))
print(a)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


**Q3.** Convert the following list to a NumPy array and print its shape:
```python
data = [[3, 5, 1], [6, 7, 9], [8, 4, 2]]
```

In [4]:
import numpy as np
data = [[3, 5, 1], [6, 7, 9], [8, 4, 2]]
a = np.array(data)
print(np.shape(a))


(3, 3)


## Practice 2: Shape & Dimensions

**Q4.** Given an array:
```python
arr = np.array([[1, 2], [3, 4], [5, 6]])
```
- What is the shape and dimension of the array?

In [5]:
import numpy as np
arr = np.array([[1, 2], [3, 4], [5, 6]])
print(np.shape(arr))
print(np.ndim(arr))

(3, 2)
2


## Practice 3: Reshaping and Transposing

**Q5.** Reshape the following array into a shape of (3, 3):
```python
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
```

In [6]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a = np.reshape(arr, (3, 3))
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


**Q6.** Transpose the reshaped array and print both.

In [7]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a = np.reshape(arr, (3, 3))
print(a)
print(a.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


**Q7.** Write a function to reverse this array.
```python
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
```

In [8]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
def reverse (arr):
    return arr[::-1]
a = reverse (arr)
print(a)

[9 8 7 6 5 4 3 2 1]


## Practice 4: Higher Dimensions

**Q8.** Create a 3D NumPy array with shape (2, 3, 4) containing numbers from 1 to 24.

In [9]:
import numpy as np
arr = np.arange(1, 25)
a = arr.reshape(2, 3, 4)
print(a)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


**Q9.** What is the `.ndim` and `.shape` of the array in Q8?

In [10]:
import numpy as np
arr = np.arange(1, 25)
a = arr.reshape(2, 3, 4)
print(a)
print(a.shape)
print(a.ndim)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
(2, 3, 4)
3


## Practice 5: Indexing and Slicing

**Q10.** Create an array from 0 to 9 and extract elements from index 2 to 6.

In [11]:
import numpy as np
arr = np.arange(10)
a = arr[2:7]
print(a)

[2 3 4 5 6]


**Q11.** Given a 2D array, retrieve the second row and the third column.

```python
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
```

In [12]:
import numpy as np
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
a = arr[1]
b = arr[:, 2]
print(a)
print(b)

[4 5 6]
[3 6 9]


## Practice 6: Array Operations

**Q12.** Create two arrays of the same shape and perform element-wise addition, subtraction, and multiplication.

In [13]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a+b)
print(a-b)
print(a*b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]


**Q13.** Compute the dot product of:
```python
a = np.array([1, 2])
b = np.array([3, 4])
```

In [14]:
import numpy as np
a = np.array([1, 2])
b = np.array([3, 4])
print(np.dot(a, b))

11


## Practice 7: Mathematical Functions
**Q14.** Use NumPy to compute the square root, exponential, and logarithm of each element in:
```python
arr = np.array([1, 4, 9, 16])
```

In [15]:
import numpy as np
arr = np.array([1, 4, 9, 16])
print(np.sqrt(arr))
print(np.exp(arr))
print(np.log(arr))

[1. 2. 3. 4.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
[0.         1.38629436 2.19722458 2.77258872]


## Practice 8: Boolean Indexing and Filtering
**Q15.** Create an array of 10 random integers between 1 and 100. Filter out the even numbers.

In [16]:
import numpy as np
arr=np.random.randint(1, 101, 10)
a=arr[arr %2 != 0]
print(arr)
print(a)

[42 86 62 64 33 45 99 75 28 36]
[33 45 99 75]
